---
apiVersion: apps/v1
kind: Deployment 
metadata : 
    name : registry-deployment
    labels : 
        app : registry-v1
spec : 
    replicas : 1 
    selector :
        matchLabels:
            app : registry-v1
    template:
        metadata : 
            labels : 
                app : registry-v1
        spec : 
            containers : 
            - name : registry-container
              image : registry:2.7.1
              ports : 
              - containerPort : 5000
                livenessProbe :
                  tcpSocket : 
                      port : 5000
                  initialDelaySeconds : 10
                readinessProbe :
                tcpSocket : 
                    port : 5000
                intialDelaySeconds : 10
            volumes:
             - name : registry-storage
               persistentVolumeClaim :
                 claimName : registry-pvs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name : registry-pvs
spec :
    accessModes : 
    - ReadWriteOnce
    resources : 
        requests :
            storage : 100Gi







