---
apiVersion: v1
kind: Service
metadata : 
    name : registry-service
spec :
    selector : 
        app : registry-v1
    ports : 
    - protocol : TCP
      port : 80
      targetPort : 5000
    type : LoadBalancer